[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "zisi"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302

[[redirects]]
  from = "/mobile"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
